// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationBarosa.DataAccess.Data;

#nullable disable

namespace WebApplicationBarosa.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240821195046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationBarosa.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("TypeOfBreed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 9,
                            TypeOfBreed = "Hunting Dogs"
                        },
                        new
                        {
                            CategoryId = 10,
                            TypeOfBreed = "Companion Dogs"
                        },
                        new
                        {
                            CategoryId = 11,
                            TypeOfBreed = "Kid-Friendly Dogs"
                        });
                });

            modelBuilder.Entity("WebApplicationBarosa.Models.Dog", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Golden Retriever",
                            CategoryId = 11,
                            Description = "Friendly and intelligent, the Golden Retriever is a popular family dog known for its gentle temperament and loyalty.",
                            Gender = 0,
                            ImageUrl = "",
                            ListPrice = 1200.0,
                            SKU = "GR9999001"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "German Shepherd",
                            CategoryId = 9,
                            Description = "Highly intelligent and versatile, the German Shepherd is an excellent working dog and family companion.",
                            Gender = 1,
                            ImageUrl = "",
                            ListPrice = 1400.0,
                            SKU = "GS777777701"
                        },
                        new
                        {
                            Id = 3,
                            Breed = "Bulldog",
                            CategoryId = 10,
                            Description = "With its distinctive wrinkled face and muscular build, the Bulldog is known for its friendly and courageous nature.",
                            Gender = 0,
                            ImageUrl = "",
                            ListPrice = 1600.0,
                            SKU = "BD5555501"
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Poodle",
                            CategoryId = 10,
                            Description = "Elegant and intelligent, the Poodle comes in various sizes and is known for its hypoallergenic coat.",
                            Gender = 1,
                            ImageUrl = "",
                            ListPrice = 1300.0,
                            SKU = "PD3333333301"
                        },
                        new
                        {
                            Id = 5,
                            Breed = "Beagle",
                            CategoryId = 9,
                            Description = "The Beagle is known for its keen sense of smell and tracking instinct, making it an excellent hunting dog.",
                            Gender = 0,
                            ImageUrl = "",
                            ListPrice = 950.0,
                            SKU = "BG1111111101"
                        },
                        new
                        {
                            Id = 6,
                            Breed = "Siberian Husky",
                            CategoryId = 11,
                            Description = "Known for its striking appearance and endurance, the Siberian Husky is a strong, energetic, and playful breed.",
                            Gender = 1,
                            ImageUrl = "",
                            ListPrice = 1500.0,
                            SKU = "SH000000001"
                        });
                });

            modelBuilder.Entity("WebApplicationBarosa.Models.Dog", b =>
                {
                    b.HasOne("WebApplicationBarosa.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
